---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin/"
webhook_url: 
sections:
- type: heading
  label: Général
- type: document
  path: data/site.yaml
  label: Options du site
- type: document
  path: data_en/site.yaml
  label: Options du site (anglais)
- type: directory
  path: data/home
  label: Page d'accueil
  create: all
  match: "**/*"
- type: directory
  path: data_en/home
  label: Page d'accueil (anglais)
  create: all
  match: "**/*"
- type: document
  path: data/pages/services.md
  label: Services Conseils
- type: document
  path: data_en/pages/services.md
  label: Services (anglais)
- type: directory
  path: data/linkedIn
  label: Ref. LinkedIn
  create: documents
  match: "**/*"
- type: directory
  path: data_en/linkedIn
  label: Ref. LinkedIn (anglais)
  create: all
  match: "**/*"
  templates:
  - ref-linkedin
- type: heading
  label: Mission
- type: directory
  path: data/ma-motivation
  label: Ma motivation
  create: all
  match: "**/*"
- type: directory
  path: data/a-propos
  label: À propos
  create: all
  match: "**/*"
- type: directory
  path: data/valeurs
  label: Mes valeurs
  create: all
  match: "**/*"
  templates:
  - content-with-image-no-position
- type: directory
  path: data/bio
  label: Compétences d'affaires
  create: all
  match: "**/*"
- type: directory
  path: data/competences-sante
  label: Compétences en santé
  create: all
  match: "**/*"
- type: directory
  path: data/outils
  label: Mes outils santé
  create: all
  match: "**/*"
  templates:
  - content-with-image-no-position
- type: directory
  path: data/soins
  label: Soins
  create: all
  match: "**/*"
- type: heading
  label: Santé et Mieux-être Individuel
- type: directory
  path: data/ameliorer-sante
  label: Améliorer santé
  create: all
  match: "**/*"
- type: directory
  path: data/carousel-perso
  label: Carousel (Ameliorer sante)
  create: all
  match: "**/*"
  templates:
  - carousel
- type: directory
  path: data/retraites
  label: Retraites
  create: all
  match: "**/*"
  templates:
  - retraites
  - content-only
- type: document
  path: data/pages/cures.md
  label: Cures
- type: heading
  label: Santé et Mieux-être Entreprise
- type: directory
  path: data/transfo-organisation
  label: Transformation Organisationnelle
  create: all
  match: "**/*"
- type: directory
  path: data/carousel
  label: Carousel (Transfo. Org)
  create: all
  match: "**/*"
  templates:
  - carousel
- type: directory
  path: data/conference-midi
  label: Conférences
  create: documents
  match: "**/*"
  templates:
  - formations
  - content-only
- type: directory
  path: data/formations
  label: Formations
  create: all
  match: "**/*"
  templates:
  - formations
  - content-only
- type: document
  path: data/pages/coaching.md
  label: Coaching Individuel
- type: directory
  path: data/pour-ton-equipe
  label: Pour ton équipe
  create: all
  match: "**/*"
- type: directory
  path: data/carousel-equipe
  label: Carousel (Pour ton equipe)
  create: all
  match: "**/*"
  templates:
  - carousel
- type: heading
  label: Ressources
- type: directory
  path: data/articles
  label: Blogue
  create: all
  match: "**/*"
  templates:
  - blogue
- type: directory
  path: data/boutique
  label: Boutique
  create: all
  match: "**/*"
  templates:
  - boutique
- type: heading
  label: Mission (anglais)
- type: directory
  path: data_en/my-purpose
  label: My Purpose
  create: all
  match: "**/*"
- type: directory
  path: data_en/about-me
  label: About Me
  create: all
  match: "**/*"
- type: directory
  path: data_en/values
  label: My Values
  create: all
  match: "**/*"
- type: directory
  path: data_en/bio
  label: Business Skills
  create: all
  match: "**/*"
  templates:
  - bio-components
  - bio
  - bio-emplois
- type: directory
  path: data_en/health-skills
  label: My Health Skills
  create: all
  match: "**/*"
- type: directory
  path: data_en/tools
  label: Tools
  create: all
  match: "**/*"
- type: directory
  path: data_en/services
  label: Care
  create: all
  match: "**/*"
- type: heading
  label: Individual Health
- type: directory
  path: data_en/health
  label: Improve my Health
  create: all
  match: "**/*"
- type: document
  path: data_en/pages/detox.md
  label: Detox
  match: "**/*"
- type: heading
  label: Corporate Wellness
- type: directory
  path: data_en/org-transfo
  label: Organizational Transformation
  create: all
  match: "**/*"
- type: directory
  path: data_en/carousel
  label: Carousel (Org.Transf)
  create: all
  match: "**/*"
  templates:
  - carousel
- type: directory
  path: data_en/training
  label: Training
  create: all
  match: "**/*"
  templates:
  - formations
- type: directory
  path: data_en/conference
  label: Conferences
  create: all
  match: "**/*"
  templates:
  - formations
- type: document
  path: data_en/pages/coaching.md
  label: Coaching
- type: heading
  label: Ressources (anglais)
- type: directory
  path: data_en/shop
  label: Shop
  create: all
  match: "**/*"
  templates:
  - boutique
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - GRAPHQL_ENDPOINT=/___graphql
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
