---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin/"
webhook_url: 
sections:
- type: heading
  label: Général
- type: document
  path: data/site.yaml
  label: Options du site
- type: directory
  path: data/home
  label: Page d'accueil
  create: all
  match: "**/*"
- type: document
  path: data/pages/services.md
  label: Services Conseils
- type: directory
  path: data/linkedIn
  label: Ref. LinkedIn
  create: documents
  match: "**/*"
- type: heading
  label: Mission
- type: directory
  path: data/ma-motivation
  label: Ma motivation
  create: all
  match: "**/*"
- type: directory
  path: data/a-propos
  label: À propos
  create: all
  match: "**/*"
- type: directory
  path: data/valeurs
  label: Mes valeurs
  create: all
  match: "**/*"
  templates:
  - content-with-image-no-position
- type: directory
  path: data/bio
  label: Compétences d'affaires
  create: all
  match: "**/*"
- type: directory
  path: data/competences-sante
  label: Compétences en santé
  create: all
  match: "**/*"
- type: directory
  path: data/outils
  label: Mes outils santé
  create: all
  match: "**/*"
  templates:
  - content-with-image-no-position
- type: heading
  label: Santé et Mieux-être Individuel
- type: directory
  path: data/ameliorer-sante
  label: Améliorer santé
  create: all
  match: "**/*"
- type: directory
  path: data/carousel-perso
  label: Carousel (Ameliorer sante)
  create: all
  match: "**/*"
  templates:
  - carousel
- type: directory
  path: data/retraites
  label: Retraites
  create: all
  match: "**/*"
  templates:
  - retraites
  - content-only
- type: document
  path: data/pages/cures.md
  label: Cures
- type: heading
  label: Santé et Mieux-être Entreprise
- type: directory
  path: data/transfo-organisation
  label: Transformation Organisationnelle
  create: all
  match: "**/*"
- type: directory
  path: data/carousel
  label: Carousel (Transfo. Org)
  create: all
  match: "**/*"
  templates:
  - carousel
- type: directory
  path: data/conference-midi
  label: Conférences
  create: documents
  match: "**/*"
  templates:
  - formations
  - content-only
- type: directory
  path: data/formations
  label: Formations
  create: all
  match: "**/*"
  templates:
  - formations
  - content-only
- type: document
  path: data/pages/coaching.md
  label: Coaching Individuel
- type: directory
  path: data/pour-ton-equipe
  label: Pour ton équipe
  create: all
  match: "**/*"
- type: directory
  path: data/carousel-equipe
  label: Carousel (Pour ton equipe)
  create: all
  match: "**/*"
  templates:
  - carousel
- type: heading
  label: Ressources
- type: directory
  path: data/articles
  label: Blogue
  create: all
  match: "**/*"
  templates:
  - blogue
- type: directory
  path: data/boutique
  label: Boutique
  create: all
  match: "**/*"
  templates:
  - boutique
- type: heading
  label: Anglais
- type: directory
  path: data_en/home
  label: Home
  create: all
  match: "**/*"
- type: directory
  path: data_en/carousel
  label: Carousel
  create: all
  match: "**/*"
  templates:
  - carousel
- type: document
  path: data_en/pages/services.md
  label: Services
- type: directory
  path: data_en/linkedIn
  label: Ref. LinkedIn
  create: documents
  match: "**/*"
  templates:
  - ref-linkedin
- type: directory
  path: data_en/training
  label: Training
  create: all
  match: "**/*"
  templates:
  - formations
- type: directory
  path: data_en/conference
  label: Conferences
  create: all
  match: "**/*"
  templates:
  - formations
- type: directory
  path: data_en/bio
  label: Bio
  create: all
  match: "**/*"
  templates:
  - bio-components
  - bio
  - bio-emplois
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - GRAPHQL_ENDPOINT=/___graphql
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
